name: Publish Docker Images to GHCR

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to GHCR
        run: echo "${{ secrets.MY_PAT }}" | docker login ghcr.io --username abrs7 --password-stdin

      - name: Build Docker Image
        run: |
          docker-compose build --no-cache web

      - name: List All Docker Images
        run: |
          docker images

      - name: Tag Docker Image
        run: |
          docker tag email_analysis_tool-web:latest ghcr.io/abrs7/email_analysis_tool:latest

      - name: Push Docker Image
        run: |
          docker push ghcr.io/abrs7/email_analysis_tool:latest
