name: Publish Docker Images to GHCR

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Log in to GHCR
        run: echo "${{ secrets.MY_PAT }}" | docker login ghcr.io --username abrs7 --password-stdin

      - name: Build Docker Image
        run: |
          docker-compose build web

      - name: List Docker Images
        run: |
          docker images | grep email_analysis_tool

      - name: Tag Docker Image
        run: |
          docker tag email_analysis_tool-web:latest ghcr.io/abrs7/email_analysis_tool:latest

      - name: Push Docker Image
        run: |
          docker push ghcr.io/abrs7/email_analysis_tool:latest

