name: Publish Docker Images to GHCR

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.MY_PAT }}" | docker login ghcr.io --username abrs7 --password-stdin

      - name: Build and Publish Docker Image
        run: |
          docker build -t ghcr.io/abrs7/email_analysis_tool:latest
          docker push ghcr.io/abrs7/email_analysis_tool:latest
